### ISSUE TITLE
Crash when VMStorage podMetadata only contains annotations

### ISSUE THREAD

**Issue by ebensom** [VictoriaMetrics/operator#264]
Error message before crash with stack trace:

```
{"level":"error","ts":1623786219.5378635,"msg":"Observed a panic: \"assignment to entry in nil map\" (assignment to entry in nil map)\ngoroutine 1461 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic(0x17dfe60, 0x1c5fff0)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x95\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x89\npanic(0x17dfe60, 0x1c5fff0)\n\truntime/panic.go:969 +0x1b9\ngithub.com/VictoriaMetrics/operator/api/v1beta1.VMCluster.VMStoragePodLabels(0x16bdb20, 0x9, 0xc002f5ff80, 0x24, 0xc003a4501c, 0x3, 0x0, 0x0, 0xc003a6a420, 0x11, ...)\n\tgithub.com/VictoriaMetrics/operator/api/v1beta1/vmcluster_types.go:744 +0x2b2\ngithub.com/VictoriaMetrics/operator/controllers/factory.makePodSpecForVMStorage(0xc006899c50, 0xc0003dd800, 0xc0058f3a70, 0x203000, 0x10)\n\tgithub.com/VictoriaMetrics/operator/controllers/factory/vmcluster.go:1300 +0x1d45\ngithub.com/VictoriaMetrics/operator/controllers/factory.GenVMStorageSpec(0xc003b985a0, 0xc0003dd800, 0x26, 0x0, 0x0)\n\tgithub.com/VictoriaMetrics/operator/controllers/factory/vmcluster.go:1083 +0x28b\ngithub.com/VictoriaMetrics/operator/controllers/factory.createOrUpdateVMStorage(0x1cb39a0, 0xc002bfb740, 0xc003b985a0, 0x1cc9ec0, 0xc0007a9130, 0xc0003dd800, 0x0, 0x0, 0x656c645855453943)\n\tgithub.com/VictoriaMetrics/operator/controllers/factory/vmcluster.go:405 +0x15b\ngithub.com/VictoriaMetrics/operator/controllers/factory.CreateOrUpdateVMCluster(0x1cb39a0, 0xc002bfb740, 0xc003b985a0, 0x1cc9ec0, 0xc0007a9130, 0xc0003dd800, 0x0, 0x0, 0x0, 0x0)\n\tgithub.com/VictoriaMetrics/operator/controllers/factory/vmcluster.go:97 +0x2da\ngithub.com/VictoriaMetrics/operator/controllers.(*VMClusterReconciler).Reconcile(0xc0001d9c20, 0x1cb39a0, 0xc002bfb740, 0xc003a6a420, 0x11, 0xc003a4501c, 0x3, 0xc002bfb740, 0x40a1df, 0xc003f10000, ...)\n\tgithub.com/VictoriaMetrics/operator/controllers/vmcluster_controller.go:67 +0x33c\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004b6500, 0x1cb38e0, 0xc000698200, 0x183d560, 0xc003ce7020)\n\tsigs.k8s.io/controller-runtime@v0.8.1/pkg/internal/controller/controller.go:297 +0x317\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004b6500, 0x1cb38e0, 0xc000698200, 0xc0021b9500)\n\tsigs.k8s.io/controller-runtime@v0.8.1/pkg/internal/controller/controller.go:252 +0x205\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x1cb38e0, 0xc000698200)\n\tsigs.k8s.io/controller-runtime@v0.8.1/pkg/internal/controller/controller.go:215 +0x4a\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0x37\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0021b9750)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00689bf50, 0x1c7a0e0, 0xc002bfb620, 0xc000698201, 0xc00068a000)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xad\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0021b9750, 0x3b9aca00, 0x0, 0x1, 0xc00068a000)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1cb38e0, 0xc000698200, 0xc003da12e0, 0x3b9aca00, 0x0, 0x1)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0xa6\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1cb38e0, 0xc000698200, 0xc003da12e0, 0x3b9aca00)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99 +0x57\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tsigs.k8s.io/controller-runtime@v0.8.1/pkg/internal/controller/controller.go:212 +0x45e\n","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.2.0/zapr.go:132\nk8s.io/klog/v2.(*loggingT).output\n\tk8s.io/klog/v2@v2.4.0/klog.go:919\nk8s.io/klog/v2.(*loggingT).printf\n\tk8s.io/klog/v2@v2.4.0/klog.go:750\nk8s.io/klog/v2.Errorf\n\tk8s.io/klog/v2@v2.4.0/klog.go:1462\nk8s.io/apimachinery/pkg/util/runtime.logPanic\n\tk8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:78\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash\n\tk8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48\nruntime.gopanic\n\truntime/panic.go:969\nruntime.mapassign_faststr\n\truntime/map_faststr.go:204\ngithub.com/VictoriaMetrics/operator/api/v1beta1.VMCluster.VMStoragePodLabels\n\tgithub.com/VictoriaMetrics/operator/api/v1beta1/vmcluster_types.go:744\ngithub.com/VictoriaMetrics/operator/controllers/factory.makePodSpecForVMStorage\n\tgithub.com/VictoriaMetrics/operator/controllers/factory/vmcluster.go:1300\ngithub.com/VictoriaMetrics/operator/controllers/factory.GenVMStorageSpec\n\tgithub.com/VictoriaMetrics/operator/controllers/factory/vmcluster.go:1083\ngithub.com/VictoriaMetrics/operator/controllers/factory.createOrUpdateVMStorage\n\tgithub.com/VictoriaMetrics/operator/controllers/factory/vmcluster.go:405\ngithub.com/VictoriaMetrics/operator/controllers/factory.CreateOrUpdateVMCluster\n\tgithub.com/VictoriaMetrics/operator/controllers/factory/vmcluster.go:97\ngithub.com/VictoriaMetrics/operator/controllers.(*VMClusterReconciler).Reconcile\n\tgithub.com/VictoriaMetrics/operator/controllers/vmcluster_controller.go:67\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.8.1/pkg/internal/controller/controller.go:297\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.8.1/pkg/internal/controller/controller.go:252\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\tsigs.k8s.io/controller-runtime@v0.8.1/pkg/internal/controller/controller.go:215\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}
```

**Troubleshooting:**
The problem is caused by [the code logic](https://github.com/VictoriaMetrics/operator/blob/master/api/v1beta1/vmcluster_types.go#L742-L745) which erroneously copies the labels map from CR and then tries to extend it with the selector labels, however the CR labels map can be nil (when not specified).

The same pattern is also observed in `VMSelectPodLabels()` and `VMInsertPodLabels()`
Please check e.g. the [`VMAlert.PodLabels()`](https://github.com/VictoriaMetrics/operator/blob/master/api/v1beta1/vmalert_types.go#L371) for the correct, nil pointer safe implementation.

**Workaround:**
Configure empty labels map in `VMStorage` / `VMInsert` / `VMSelect`, e.g.:

```
[...]
  podMetadata:
    labels: {}
    annotations:
      foo: bar
```

**Comment by f41gh7** [comment]
Thanks for reporting, will be fixed soon.

**Comment by f41gh7** [comment]
related PR must fix it, soon hot-fix patch will be released.
